import type { Product } from "./types"

// Mock products for development - Replace with your actual products
// These will be used when Supabase is not connected
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Handcrafted Ceramic Vase",
    description: "Beautiful handmade ceramic vase with a modern minimalist design. Perfect for fresh or dried flowers. Each piece is unique with subtle variations in glaze.",
    price: 2499,
    image: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&h=600&fit=crop",
    category: "Home Decor",
    stock: 15,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Natural Linen Table Runner",
    description: "Elegant linen table runner made from 100% natural flax. Adds a touch of sophistication to any dining setup. Machine washable and durable.",
    price: 1299,
    image: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=600&h=600&fit=crop",
    category: "Home Decor",
    stock: 25,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Wooden Serving Board",
    description: "Premium acacia wood serving board, perfect for cheese, charcuterie, or appetizers. Food-safe finish with natural grain patterns.",
    price: 1899,
    image: "https://images.unsplash.com/photo-1605001011156-cbf0b0f67a51?w=600&h=600&fit=crop",
    category: "Kitchen",
    stock: 20,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Minimalist Desk Lamp",
    description: "Modern LED desk lamp with adjustable brightness and color temperature. Sleek design fits any workspace. USB powered for convenience.",
    price: 3499,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop",
    category: "Lighting",
    stock: 12,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Organic Cotton Throw Blanket",
    description: "Soft and cozy throw blanket made from 100% organic cotton. Perfect for cool evenings on the couch. Available in neutral tones.",
    price: 2799,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop",
    category: "Textiles",
    stock: 18,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Brass Candle Holders (Set of 3)",
    description: "Elegant brass candle holders in three different heights. Creates beautiful ambient lighting. Perfect for mantels or dining tables.",
    price: 1999,
    image: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600&h=600&fit=crop",
    category: "Home Decor",
    stock: 10,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Bamboo Storage Baskets",
    description: "Set of 2 handwoven bamboo baskets for stylish storage. Great for organizing shelves, closets, or living spaces. Durable and eco-friendly.",
    price: 1599,
    image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=600&h=600&fit=crop",
    category: "Storage",
    stock: 30,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Artisan Coffee Mug Set",
    description: "Set of 4 handcrafted stoneware mugs with unique glazing. Microwave and dishwasher safe. Each mug holds 350ml.",
    price: 2199,
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&h=600&fit=crop",
    category: "Kitchen",
    stock: 22,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Get unique categories from products
export const CATEGORIES = [...new Set(MOCK_PRODUCTS.map((p) => p.category))]
